enable = true
enableDebugWindow = false
#Allowed Values: DEFAULT, SIMPLE, COMPLETE
style = "DEFAULT"

[windowGroup]
	enableWindow = false
	disableNames = ["None"]
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	windowMoveDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	windowMoveEase = "OUT_BACK"
	# Default: 0.0
	# Range: -10000.0 ~ 10000.0
	windowMoveX = 0.0
	# Default: 50.0
	# Range: -10000.0 ~ 10000.0
	windowMoveY = 50.0
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	windowGradientDuration = 8.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	windowGradientEase = "IN_OUT_SINE"
	enableJei = false
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	jeiMoveDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	jeiMoveEase = "OUT_BACK"
	# Default: -50.0
	# Range: -10000.0 ~ 10000.0
	jeiMoveX = -50.0
	# Default: 0.0
	# Range: -10000.0 ~ 10000.0
	jeiMoveY = 0.0
	enableCloseWindow = false
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	closeMoveDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	closeMoveEase = "IN_OUT_SINE"
	# Default: 0.0
	# Range: -10000.0 ~ 10000.0
	closeMoveX = 0.0
	# Default: 300.0
	# Range: -10000.0 ~ 10000.0
	closeMoveY = 300.0
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	closeGradientDuration = 8.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	closeGradientEase = "IN_OUT_SINE"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	closeJeiMoveDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	closeJeiMoveEase = "IN_OUT_SINE"
	# Default: -300.0
	# Range: -10000.0 ~ 10000.0
	closeJeiMoveX = -300.0
	# Default: 0.0
	# Range: -10000.0 ~ 10000.0
	closeJeiMoveY = 0.0

[screenItemGroup]
	enableHover = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	hoverDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	hoverEase = "IN_OUT_SINE"
	# Default: 1.2
	# Range: 1.0 ~ 10.0
	hoverScale = 1.0
	enableTooltip = false
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	tooltipDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	tooltipEase = "OUT_CIRC"
	# Default: 1.2
	# Range: 0.0 ~ 1000.0
	clickItemScale = 1.0
	enableClickItem = true
	# Default: 0.2
	# Range: 0.0 ~ 1000.0
	clickZoomStrength = 0.1
	# Default: 5.0
	# Range: 0.0 ~ 1000.0
	clickItemDuration = 2.0
	enableOutput = true
	# Default: 5.0
	# Range: 0.0 ~ 1000.0
	outputDuration = 3.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	outputEase = "OUT_BACK"
	enableDrag = false
	# Default: 15.0
	# Range: 0.0 ~ 90.0
	dragMaxAngle = 15.0
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	dragSensitivity = 8.0
	enableQuick = true
	enableSameItem = true
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	sameItemDelay = 10.0
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	sameItemShakeStrength = 0.15
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	sameItemShakeDuration = 15.0
	# Default: 1.0
	# Range: 0.0 ~ 1000.0
	sameItemShakeFrequency = 0.5
	# Default: 20.0
	# Range: 0.0 ~ 1000.0
	sameItemShakeWaitDuration = 10.0
	enableMove = true
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	moveDuration = 1.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	moveEase = "OUT_SINE"
	enableFinish = false
	# Default: 0.2
	# Range: 0.0 ~ 1000.0
	finishPunchStrength = 0.2
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	finishDuration = 6.0
	enablePickup = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	pickupDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	pickupEase = "IN_OUT_SINE"
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	quickCraftDuration = 400.0

[hotbarGroup]
	enableHoldItem = false
	enableHoldZoomTransition = false
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	holdZoomInDuration = 8.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	holdZoomInEase = "OUT_QUINT"
	# Default: 1.4
	# Range: 1.0 ~ 10.0
	holdZoomScale = 1.4
	# Default: 2.0
	# Range: 0.0 ~ 1000.0
	holdZoomOutDuration = 2.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	holdZoomOutEase = "OUT_QUART"
	enableLack = false
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	lackDuration = 2.0
	# Default: 3.0
	# Range: 0.0 ~ 1000.0
	lackShakeStrength = 0.5
	enableExp = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	expDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	expEase = "OUT_BACK"
	# Default: 4.0
	# Range: 1.0 ~ 1000.0
	expScale = 2.0
	enableSelectedItemName = false
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	selectedItemNameMoveDuration = 4.0
	# Default: 5.0
	# Range: 0.0 ~ 1000.0
	selectedItemNameMoveY = 5.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	selectedItemNameMoveEase = "IN_OUT_SINE"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	selectedItemNameAlphaDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	selectedItemNameAlphaEase = "IN_OUT_SINE"
	enableAttack = true
	# Default: 15.0
	# Range: 0.0 ~ 90.0
	attackMaxAngle = 5.0
	enableUse = false
	# Default: 0.20000000298023224
	# Range: 0.0 ~ 1000.0
	useStrength = 0.1
	enableSelectMove = true
	enableArmor = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	armorDuration = 4.0
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	upArmorScale = 1.5
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	upArmorEase = "IN_OUT_SINE"
	# Default: 3.0
	# Range: 0.0 ~ 1000.0
	downArmorShakeStrength = 3.0
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	selectMoveSpeed = 3.0

[chatGroup]
	enableChat = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	chatOpenMoveDuration = 3.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatOpenMoveEase = "OUT_QUAD"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	chatOpenGradientDuration = 3.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatOpenGradientEase = "IN_OUT_SINE"
	enableChatComp = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	chatCompMoveDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatCompMoveEase = "OUT_QUAD"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	chatCompGradientDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatCompGradientEase = "IN_OUT_SINE"
	enableCloseChat = true
	# Default: 1.2000000476837158
	# Range: 0.0 ~ 1000.0
	closeChatSpeed = 1.2000000476837158

[bossGroup]
	enableBossShow = true
	# Default: 10.0
	# Range: 0.0 ~ 1000.0
	bossShowDuration = 15.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossShowEase = "OUT_CIRC"
	# Default: 10.0
	# Range: 0.0 ~ 1000.0
	bossShowFadeDuration = 10.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossShowFadeEase = "IN_OUT_SINE"
	enableBossHide = true
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	bossHideDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossHideEase = "IN_OUT_SINE"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	bossHideFadeDuration = 8.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossHideFadeEase = "IN_OUT_SINE"
	enableBossHurt = true
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	bossHurtShakeStrength = 3
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	bossHurtDuration = 3.0
