#Adds badge to mod in this format "modid=badge1, badge2"
mod_badges = [
	"kubejs=modpack",
	"almanac=library",
	"createdeco=modpack",
	"playeranimator=library",
	"_decoration=modpack",
	"_quality_of_life=modpack",
	"neoforge=library, sinytra_neoforge",
	"yungsapi=library",
	"server_i18n_api=library",
	"balm=library",
	"prickle=library",
	"_visuals_and_sound=modpack",
	"curios=library",
	"searchables=library",
	"emiffect=client",
	"unilib=library",
	"sliceanddice=modpack",
	"colorwheel_patcher=client",
	"preloading_tricks=library",
	"libraryferret=library",
	"glitchcore=library",
	"midnightlib=library",
	"runiclib=library",
	"emi_create_schematics=client",
	"emi=client",
	"terrablender=library",
	"bettercombat=modpack",
	"ohthetreesyoullgrow=library",
	"corgilib=library",
	"kotlinforforge=library",
	"puzzleslib=library",
	"_development=modpack",
	"configurable=library",
	"jinxedlib=library",
	"globalpacks=modpack",
	"geckolib=library",
	"emi_loot=client",
	"bookshelf=library",
	"fzzy_config=library",
	"remi=client",
	"collective=library",
	"resourcefullib=library",
	"architectury=library",
	"mru=library",
	"moogs_structures=library",
	"dataanchor=library",
	"rhino=library",
	"owo=library",
	"octolib=library",
	"commonnetworking=library",
	"particlerain=client, modpack",
	"invmove=modpack",
	"create=modpack",
	"create_bic_bit=modpack",
	"mod_sets=modpack, !library",
	"ezactions=modpack, client",
	"particular=client, modpack",
	"txnilib=library",
	"_world_generation=modpack",
	"moonlight=library",
	"creativecore=library",
	"_optimization=modpack",
	"via_romana=modpack",
	"cobblemore_lib=library",
	"iceberg=library",
	"coroutil=library",
	"emi_enchanting=client",
	"_management=modpack",
	"ferritecore=client",
	"yet_another_config_lib_v3=library",
	"colorwheel=client",
	"lodestone=library"
]
#Make mods apear under another mod in this format "parenModId=childId1, childId2", add ! at the beginning of parentId to prevent creating a fake parent
mod_parents = [
	"!chunky=chunkyborder",
	"!yungscavebiomes=yungsapi",
	"!craftingtweaks=balm",
	"!jade=jadeaddons",
	"!gag=placebo",
	"!colorwheel=colorwheel_patcher",
	"!bettercaves=yungsapi",
	"!mns=moogs_structures",
	"!mr_dungeons_andtaverns=mr_dungeons_andtavernsjungletemplereplacement, mr_dungeons_andtavernsoceanmonumentreplacement",
	"!urban_decor=runiclib",
	"!sodium=iris",
	"!iris=colorwheel",
	"!mvs=moogs_structures",
	"!bridgingmod=yet_another_config_lib_v3",
	"!mega_showdown=zamega",
	"!yungsextras=yungsapi",
	"!lambdynlights=lambdynlights_api, lambdynlights_runtime",
	"!c2me=c2me_base, c2me_client_uncapvd, c2me_fixes_chunkio_threading_issues, c2me_fixes_general_threading_issues, c2me_fixes_worldgen_threading_issues, c2me_fixes_worldgen_vanilla_bugs, c2me_notickvd, c2me_opts_chunkio, c2me_opts_dfc, c2me_opts_worldgen_general, c2me_opts_math, c2me_opts_allocs, c2me_opts_natives_math, c2me_opts_scheduling, c2me_opts_worldgen_vanilla, c2me_rewrites_chunkio, c2me_rewrites_chunk_system, c2me_server_utils, c2me_threading_lighting",
	"!mss=moogs_structures",
	"!invmove=invmove_compat",
	"!arts_and_crafts=jinxedlib",
	"!biomeswevegone=corgilib, geckolib, ohthetreesyoullgrow, terrablender",
	"!firespreadtweaks=armorstatues, collective",
	"!snowyspirit=moonlight",
	"!supplementaries=moonlight",
	"_decoration=immersive_paintings, arts_and_crafts, handcrafted, immersive_furniture, connectiblechains, shutterup, urban_decor",
	"_development=atlasviewer, eggpreview, nbtac, packdev_toolkit, panoptic, probejs, resource_explorer, viewboard",
	"_management=chunky, defaultoptions, ezactions, globalpacks, neruina, resource_world, smart_item_deleter_v2, spark",
	"!artifacts=reliquified_artifacts",
	"!mod_menu=modlistmemory",
	"!kubejs=kubejs_create, lootjs, probejs",
	"!cobblemon=cobblemon_battle_extras, capture_xp, mr_cobblemon_journeymounts, cobblemonraiddens, mega_showdown, cobblemonintegrations, cobblenav, cobbreeding, createmonballsoverhaul, kotlinforforge, lootrmon, rctmod, rctapi, tim_core, tmtcobfarm",
	"!create=bits_n_bobs, createmonballsoverhaul, createdeco, create_ltab, sliceanddice, create_bic_bit, copycats, create_deepfried, emi_create_schematics, curios, kubejs_create, sophisticatedbackpackscreateintegration, sophisticatedstoragecreateintegration",
	"!cnc=geckolib",
	"!cpm=cpmsvcc",
	"!farmersdelight=brewinandchewin, sliceanddice, displaydelight, minersdelight, mynethersdelight, repurposed_structures_farmers_delight_compat",
	"!mowziesmobs=geckolib",
	"!relics=curios, reliquified_artifacts",
	"!voicechat=cpmsvcc, voicechat_api",
	"!sophisticatedbackpacks=accessories, curios, sophisticatedbackpackscreateintegration, sophisticatedcore, sophisticateditemactions, sophisticatedfix, sophisticatedsorter",
	"!sophisticatedstorage=sophisticatedcore, sophisticateditemactions, sophisticatedstoragecreateintegration, sophisticatedfix, sophisticatedsorter",
	"!xaerominimap=maplink, xaerotrainmap, xaeroworldmap, xaerolib",
	"!copperagebackport=cab_registry_compat",
	"!emi=emi_create_schematics, emi_enchanting, emi_loot, emiffect, remi, toomanyrecipeviewers, emirecipesharing",
	"_optimization=asynclogger, cerulean, c2me, dynamic_fps, entityculling, ferritecore, immediatelyfast, immersive_optimization, letmedespawn, lithium, modernfix, particle_core, resourcetrimmer, saturn, servercore, sodium",
	"!armorstatues=statuemenus",
	"_quality_of_life=advancements_reloaded, appleskin, armorstatues, betterf3, bridgingmod, carryon, cleanertooltips, clientdoubledoors, clutternomore, constructionstick, controlling, craftingtweaks, crawl, drizzleproof, explorerscompass, extendedhotbar, firespreadtweaks, gag, gravestone, treechop, invmove, jade, justhammers, mendingrework, mousetweaks, naturescompass, nbtedit, notenoughcrashes, one_click_join, persistentcreativeinventory, persistentinventorysearch, polymorph, rrls, searchstats, smalldoubling, sneaky_link, sortedcreativetabs, soulbound, usefulspyglass, via_romana, yo_hooks, easybuilding",
	"_visuals_and_sound=smoothskies, simplefog, advancementplaques, arrowtrails, beb, beautiful_potions, chunksfadein, colorfulhearts, effectdescriptions, emojis, enchdesc, guitween, highly_customizable_damage_numbers, item_interactions_mod, lambdynlights, more_sounds, notenoughanimations, particlerain, particular, seasonalambiance, sound_physics_remastered, sounds, tipsmod",
	"_world_generation=awesomedungeon, awesomedungeonocean, biomesoplenty, mr_dungeons_andtaverns, mns, mvs, mss, biomeswevegone, repurposed_structures, sparsestructures, temperaturebands, the_bumblezone, underground_bunkers, undergroundworlds, bettercaves, yungscavebiomes, yungsextras",
	"!waterframes=watermedia, watermedia_youtube_plugin, watervision"
]

[main]
	#Allowed Values: ASCENDING, DESCENDING
	sorting = "ASCENDING"
	#Makes list more compacted
	compact_list = false
	#Allowed Values: CLASSIC, REPLACE_REALMS, SHRINK, SHRINK_LEFT, ICON
	mods_button_style = "REPLACE_REALMS"
	#Allowed Values: REPLACE, INSERT, ICON
	game_menu_button_style = "REPLACE"
	#Allowed Values: TITLE_SCREEN, MODS_BUTTON, TITLE_SCREEN_AND_MODS_BUTTON, NONE
	mod_count_location = "TITLE_SCREEN"
	#Shows secret mod count translations defined by modmenu.mods.MOD_COUND.secret
	easter_eggs = true
	#Makes java mod have random colors
	random_java_colors = false
	#Make mod names translatable defining by modmenu.nameTranslation.modid
	translate_names = true
	#Make mod descriptions translatable defining by modmenu.descriptionTranslation.modid
	translate_descriptions = true
	#Shows config button above mod icon on the left
	quick_configure = true
	#Modifies title screen, if false will be neoforge default with default mods button
	modify_title_screen = true
	#Changes pause screen's button position and replaces neoforge's mods button with better modlist's one
	modify_game_menu = true
	#Will only show mods with config available
	config_mode = false
	#Disables drag and drop mods adding
	disable_drag_and_drop = true
	#Will use catalogue's icon if present
	use_catalogue_icon = true
	#Allows to edit mod badges and parents ingame by dragging or button
	editor_mode = false

[hide]
	#Shows mods with library badge
	show_libraries = true
	#Hides links of the mod
	hide_mod_links = false
	#Hides mod's license
	hide_mod_license = false
	#Hides mod's badges
	hide_badges = false
	#Add id of the badge to hide it
	hide_badge = []
	#Hides mod's credits
	hide_mod_credits = false
	#Hides mod's config button
	hide_config_buttons = false
	#Hides search bar and drag and drop text, also moves mod's icon up
	hide_screen_top = false
	#Add modid of the mod to hide it from the modlist
	hidden_mods = []
	#Add modid of the mod to hide its config
	hidden_configs = []
	#deprecated
	library_list = []

	#deprecated
	[hide.disable_default_badges_section]
		disable_default_badges_all = false
		disable_default_badges = []

[count]
	#Makes hidden mods count added to the total mods count
	count_hidden_mods = false
	#Makes childrens count get added to the total mods count
	count_children = true
	#Makes libraries count get added to the total mods count
	count_libraries = false
